baseURL = "https://example.com"
languageCode = "en-us"
resourceDir = "../resources"
theme = "pcw-hugo-theme"
themesDir = "../.."
title = "Notre-Dame de Paris"

DefaultContentLanguage = "en" 
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
SectionPagesMenu = "main" 
enableRobotsTXT = true 
googleAnalytics = "" 

[languages]
[languages.en]
contentDir = "content/en"
title = "My blog"
weight = 1
[languages.fr]
contentDir = "content/fr"
title = "Mon blogue"
weight = 2

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[params]
description = "The last theme you'll ever need. Maybe."
facebook = ""
favicon = ""
github = ""
gitlab = ""
instagram = ""
linkedin = ""
mastodon = ""
rss = ""
site_logo = ""
slack = ""
stackoverflow = ""
twitter = "https://twitter.com/GoHugoIO"
youtube = ""
# choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
featured_image = "/images/gohugo-default-sample-hero-image.jpg"
recent_posts_number = 2
